version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5673:5672"       # RabbitMQ main port
      - "15673:15672"     # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - sistema-ibt-network

  app:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      - sistema-ibt-network

networks:
  sistema-ibt-network:
    external: true
