services:
  rabbitmq:
    build: .
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - rabbitmq-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  rabbitmq-net:
    driver: bridge
